name: Issues - Project Stage sync

on:
  issues:
    types: [opened, edited, reopened, closed, labeled, unlabeled]

permissions:
  contents: read

jobs:
  call:
    uses: Ethan-Personal/.github/.github/workflows/reusable-project-stage-sync.yml@main
    with:
      project_number: ${{ vars.PROJECT_NUMBER }}
      project_name: Workflow
      stage_field_name: Stage
    secrets:
      ORG_WORKFLOW_TOKEN: ${{ secrets.ORG_WORKFLOW_TOKEN }}